---
development:
  cloud_name: ENV[CLOUDINARY_CLOUD_NAME]
  api_key: ENV[CLOUDINARY_KEY]
  api_secret: ENV[CLOUDINARY SECRET]
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: ENV[CLOUDINARY_CLOUD_NAME]
  api_key: ENV[CLOUDINARY_KEY]
  api_secret: ENV[CLOUDINARY SECRET]
  enhance_image_tag: true
  static_file_support: false

